export const SEED_PRODUCTS = [
  {
    name: "Laptop Acer Swift 3",
    category: "Laptop",
    price: 10500000,
    specs: {
      processor: "Intel Core i7-13th Gen",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      display: '14" FHD IPS',
      gpu: "Intel Iris Xe",
      weight: "1.25 kg",
      battery: "56Wh, hingga 9 jam",
    },
  },
  {
    name: "Laptop ASUS TUF Gaming F15",
    category: "Laptop",
    price: 14999000,
    specs: {
      processor: "Intel Core i5-12500H",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      display: '15.6" FHD 144Hz',
      gpu: "NVIDIA RTX 3050 4GB",
      weight: "2.2 kg",
      cooling: "Dual fan anti-dust",
    },
  },
  {
    name: "Laptop Lenovo IdeaPad Slim 3",
    category: "Laptop",
    price: 7299000,
    specs: {
      processor: "AMD Ryzen 5 7520U",
      ram: "8GB LPDDR5",
      storage: "512GB SSD",
      display: '15.6" FHD',
      gpu: "AMD Radeon 610M",
      weight: "1.62 kg",
    },
  },
  {
    name: "MacBook Air M2",
    category: "Laptop",
    price: 16499000,
    specs: {
      processor: "Apple M2 8-core",
      ram: "8GB Unified",
      storage: "256GB SSD",
      display: '13.6" Liquid Retina',
      gpu: "Apple 8-core GPU",
      weight: "1.24 kg",
      battery: "hingga 18 jam",
    },
  },
  {
    name: "Smartphone Samsung Galaxy A55",
    category: "Smartphone",
    price: 5999000,
    specs: {
      chipset: "Exynos 1480",
      ram: "8GB",
      storage: "256GB",
      display: '6.6" Super AMOLED 120Hz',
      camera: "50MP OIS + 12MP UW + 5MP",
      battery: "5000mAh, 25W",
    },
  },
  {
    name: "Smartphone Xiaomi Redmi Note 13 Pro",
    category: "Smartphone",
    price: 3899000,
    specs: {
      chipset: "Snapdragon 7s Gen 2",
      ram: "8GB",
      storage: "256GB",
      display: '6.67" AMOLED 120Hz',
      camera: "200MP OIS",
      battery: "5100mAh, 67W turbo charge",
    },
  },
  {
    name: "Smartphone iPhone 15",
    category: "Smartphone",
    price: 13499000,
    specs: {
      chipset: "Apple A16 Bionic",
      ram: "6GB",
      storage: "128GB",
      display: '6.1" Super Retina XDR',
      camera: "48MP + 12MP UW",
      battery: "hingga 20 jam video",
    },
  },
  {
    name: "Monitor LG UltraGear 27GN800",
    category: "Monitor",
    price: 4299000,
    specs: {
      size: "27 inch",
      resolution: "2560x1440 QHD",
      refreshRate: "144Hz",
      panel: "Nano IPS 1ms",
      ports: "2x HDMI, 1x DisplayPort",
      features: "G-Sync Compatible, HDR10",
    },
  },
  {
    name: "Monitor Xiaomi A24i",
    category: "Monitor",
    price: 1099000,
    specs: {
      size: "23.8 inch",
      resolution: "1920x1080 FHD",
      refreshRate: "100Hz",
      panel: "IPS",
      ports: "1x HDMI, 1x VGA",
    },
  },
  {
    name: "Tablet Samsung Galaxy Tab S9 FE",
    category: "Tablet",
    price: 6999000,
    specs: {
      chipset: "Exynos 1380",
      ram: "6GB",
      storage: "128GB",
      display: '10.9" 90Hz',
      battery: "8000mAh",
      extras: "S-Pen included, IP68",
    },
  },
  {
    name: "Mouse Logitech MX Master 3S",
    category: "Aksesoris",
    price: 1549000,
    specs: {
      sensor: "8000 DPI Darkfield",
      connection: "Bluetooth / Logi Bolt",
      battery: "70 hari per charge",
      buttons: "7 tombol, MagSpeed scroll",
      compatibility: "Windows, macOS, Linux",
    },
  },
  {
    name: "Keyboard Keychron K2 V2",
    category: "Aksesoris",
    price: 1299000,
    specs: {
      layout: "75% (84 keys)",
      switch: "Gateron Brown (hot-swap)",
      connection: "Bluetooth 5.1 / USB-C",
      backlight: "RGB",
      compatibility: "Windows & macOS",
    },
  },
];
